### PR TITLE
Update MainActivity.java

### PR DESCRIPTION
**Pull request by BarBrandwine**
finalized

### CODE REVIEW

**Comment by talboren** [comment]
@BarBrandwine please see that "Files changed" contains 1 file only, where are the rest of the files? are they already in master?

**Review by talboren — CHANGES_REQUESTED** [review]
Open the pull request once again with all of the files so we can actually see the work you did.

**Comment by BarBrandwine** [comment]
@talboren Everything is on master, in order for you to review it do I need to make a new pull request?

**Comment by talboren** [comment]
@ransh93 @BarBrandwine I'll review the code on master **but for next time**, code should be developed in a separate branch and then, when you are done, code should be pushed to master by a pull request (what we're doing right now), after a code review.

**Pull request merged**
